dashboard/urls.py
from django.urls import path,include
from . import views
from dashboard.views import UserRoleCreateView

urlpatterns = [
    path('',views.admin_login, name='gw-admin'),
    path('signout/',views.signout, name='logout'),
    # path('',views.LoginView.as_view(),name='gw-admin'),
    path('base/',views.dashboard, name='index'),
    path('user/',views.index, name='dash_board'),
    # path('role/',views.role,name='role'),
    path('general/',views.general,name='general'),
    path('local/',views.local,name='local'),
    path('server/',views.server,name='server'),
    path('stock/',views.stock,name='stock'),
    path('order_status/',views.order_status,name='order_status'),
    path('tax/',views.tax,name='tax'),
    path('currency/',views.currency,name='currency'),
    path('detail/',views.detail,name='detail'),
    path('detail<int:id>/',views.detail,name='detail'),
    path('social/',views.social,name='social'),
    path('role/',views.UserRoleCreateView.as_view(),name='role')
]

dashboard/models.py
from django.db import models

from django.utils.translation import gettext_lazy as _
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models 
from django_countries.fields import CountryField
from babel.numbers import list_currencies
from languages.fields import LanguageField




# Create your models here.
class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class Role(models.Model):
    name = models.CharField(max_length=30)
    created = models.DateField(auto_now_add=True)
    order = models.BooleanField(_('order'),default=False)
    catolog = models.BooleanField(_('catolog'),default=False)
    pages = models.BooleanField(_('pages'),default=False)
    subscribers_list = models.BooleanField(_('subscribers_list'),default=False)
    report = models.BooleanField(_('report'),default=False)

    def __str__ (self):
        return self.name


class User(AbstractUser):
    """User model."""

    username = None
    email = models.EmailField(_('email address'), unique=True)
    full_name = models.CharField(max_length=30)
    # first_name=models.CharField(max_length=120)
    # last_name=models.CharField(max_length=123)
    # is_staff = models.BooleanField(default=True)
    role = models.ForeignKey(to=Role, on_delete=models.CASCADE,null=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']

    objects = UserManager()

    def _str_(self):
        """ Return string representation of our user """
        return self.email






class Store(models.Model):
    meta_title = models.CharField(max_length=30)
    meta_description = models.TextField()
    store_logo = models.ImageField(upload_to='media',null=True,blank=True)
    store_name = models.CharField(max_length=50)
    address = models.TextField()
    email = models.EmailField()
    phone = models.CharField(max_length=30)


    def __str__(self):
        return self.store_name


class Local(models.Model):
    LOCAL_CHOICES = (
        ('ACDT', 'ACST'),
        ('ACT', 'ACWST'),
    )

    timezone = models.CharField(max_length=50, choices=LOCAL_CHOICES)
    # language = LanguageField(max_length=30, blank= True)

    country = CountryField(blank=True)
    CURRENCY_CHOICES = [(currency, currency) for currency in list_currencies()] 
    currency = models.CharField(
        max_length=3, null=True, blank=True, choices=CURRENCY_CHOICES
    )
    currency_with_default = models.CharField(
        max_length=3, default='USD', choices=CURRENCY_CHOICES
    )
  
    def __str__(self):
        return self.timezone




class Tax(models.Model):
    TAX_CHOICES = (
        ('VAT', 'VAT'),
        ('GST', 'GST'),
    )

    tax_name = models.CharField(max_length=50)
    tax_rate = models.DecimalField(decimal_places=2, max_digits=10)
    type = models.CharField(max_length=50, choices=TAX_CHOICES)
    date_joined =models.DateField()
    date_modified = models.DateField()

    def __str__(self):
        return self.tax_name

class Coins(models.Model):
    STATUS_CHOICES = (
        ('ACTIVE', 'ACTIVE'),
        ('INACTIVE', 'INACTIVE'),
    )

    CURRENCY_CHOICES = [(currency, currency) for currency in list_currencies()] 
    currency_title = models.CharField(
        max_length=3, null=True, blank=True, choices=CURRENCY_CHOICES
    )
    code = models.CharField(max_length=30)
    decimal_places= models.DecimalField(decimal_places=2, max_digits=10)
    symbol = models.CharField(max_length=10)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)

    

class OrderStatus(models.Model):
    
    ORDER_CHOICES = (
        ('PENDING', 'PENDING'),
        ('SUCCESS', 'SUCCESS'),
    )

    status =  models.CharField(
    max_length=10,
    choices=ORDER_CHOICES,
    default= 'PENDING')

class StockStatus(models.Model):
    STOCK_CHOICES = (
        ('PENDING', 'PENDING'),
        ('SUCCESS', 'SUCCESS'),
    )
    status =  models.CharField(
    max_length=10,
    choices=STOCK_CHOICES,
    )

class Social(models.Model):
    SOCIAL_CHOICES = (
        ('ACTIVE', 'ACTIVE'),
        ('DEACTIVE', 'DEACTIVE'),
    )


    name = models.CharField(max_length=30)
    icon = models.CharField(max_length=50)
    url = models.CharField(max_length=50)
    status = models.CharField(max_length=10, choices=SOCIAL_CHOICES)

dashboard/forms.py
from django import forms
# from django.contrib.auth.models import User
from . models import Role,User,Store,Local,OrderStatus,StockStatus,Tax,Social,Coins



class RoleForm(forms.ModelForm):
   

    class Meta:
        model= Role
        fields = '__all__'


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields =['full_name','email','role']


        widgets={
            'full_name':forms.TextInput(attrs={'class':'form-control','placeholder': 'Name'}),
            
            'email':forms.EmailInput(attrs={'class':'form-control','placeholder': 'Email'}),
            
            'role': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Select', 'min': 8}),
        }


class StoreForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = ['meta_title','meta_description','email','store_logo','store_name','address','phone']

        widgets = {
            'meta_title':forms.TextInput(attrs={'class':'form-control','placeholder': 'meta_title'}),
            'meta_description':forms.TextInput(attrs={'class':'form-control','placeholder': 'meta_description'}),
            'email':forms.EmailInput(attrs={'class':'form-control','placeholder': 'Email'}),
            'store_logo':forms.FileInput(attrs={'class':'form-control','placeholder': 'store_logo'}),
            'store_name':forms.TextInput(attrs={'class':'form-control','placeholder': 'store_name'}),
            'address':forms.TextInput(attrs={'class':'form-control','placeholder': 'address'}),
            'phone':forms.TextInput(attrs={'class':'form-control','placeholder': 'phone'}),
        }

class LocalForm(forms.ModelForm):
    class Meta:
        model = Local
        fields = ['country','currency','timezone']

        widgets = {
            'country':forms.Select(attrs={'class':'form-control','placeholder': 'country'}),
            'currency':forms.Select(attrs={'class':'form-control','placeholder': 'currency'}),
            'timezone':forms.Select(attrs={'class':'form-control','placeholder': 'timezone'}),
            # 'language':forms.textInput(attrs={'class':'form-control','placeholder': 'store_logo'}),
            
        }

class OrderStatusForm(forms.ModelForm):
    class Meta:
        model = OrderStatus
        fields = ['status']

        widgets = {
            'status':forms.Select(attrs={'class':'form-control','placeholder':'status'})
        }

class StockStatusForm(forms.ModelForm):
    class Meta:
        model = StockStatus
        fields = ['status']

        widgets = {
            'status':forms.Select(attrs={'class':'form-control','placeholder':'status'})
        }


class TaxForm(forms.ModelForm):
    class Meta:
        model = Tax
        fields = '__all__'

        widgets = {
            'tax_name':forms.TextInput(attrs={'class':'form-control','placeholder': 'title'}),
            'tax_rate':forms.NumberInput(attrs={'class':'form-control','placeholder': 'rate'}),
            'type':forms.Select(attrs={'class':'form-control','placeholder': 'type'}),
            'date_joined':forms.DateInput(attrs={'class':'form-control','placeholder': 'date'}),
            'date_modified':forms.DateInput(attrs={'class':'form-control','placeholder': 'date_added'}),
            
        }
class SocialForm(forms.ModelForm):
    class Meta:
        model = Social
        fields = '__all__'

        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control','placeholder': 'name'}),
            'icon':forms.TextInput(attrs={'class':'form-control','placeholder': 'icon'}),
            'status':forms.Select(attrs={'class':'form-control','placeholder': 'status'}),
            'url':forms.TextInput(attrs={'class':'form-control','placeholder': 'url'}),
            
        }

class CoinsForm(forms.ModelForm):
    class Meta:
        model=Coins
        fields='__all__'   
        widgets = {
            'currency_title':forms.Select(attrs={'class':'form-control','placeholder': 'currency_title'}),
            'code':forms.TextInput(attrs={'class':'form-control','placeholder': 'code'}),
            'decimal_places':forms.NumberInput(attrs={'class':'form-control','placeholder': 'decimal_places'}),
            'symbol':forms.TextInput(attrs={'class':'form-control','placeholder': 'symbol'}),
            'status':forms.Select(attrs={'class':'form-control','placeholder': 'status'}),
        }
   

dashboard/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from . forms import RoleForm,UserForm,StoreForm,LocalForm,OrderStatusForm,StockStatusForm,TaxForm,SocialForm,CoinsForm
from django.views.generic import View,CreateView,FormView,TemplateView
from django.contrib import messages
from . models import Store,Local,Tax,Coins,OrderStatus,Social,StockStatus,User,Role
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
# Create your views here.




def admin_login(request):

        if request.method == 'POST':


                email = request.POST.get('email')
                password = request.POST.get('password')
                #     user_obj = User.objects.filter(email=email)

                user_obj = authenticate(request,email=email,password=password)
                print(user_obj,'===============')
                
                if user_obj.is_staff :
                        
                        login(request, user_obj)
                        return redirect('index')

                       
                elif user_obj.is_superuser:
                        
                        login(request, user_obj)
                        return redirect('index')

        else:
                return render(request,'dashboard/login.html')



# class LoginView(TemplateView):
#     template_name='dashboard/login.html'
#     def post(self,request):
#         email= request.POST.get('email')
#         password= request.POST.get('password')
#         user=authenticate(request,email=email,password=password)
#         print('*******************',user)
#         if user:
#             login(request,user)
#             # messages.success(request,'Login successful')
#             return redirect("admin_dashboard")
#         messages.error(request,"Invalid username or password")
#         return render(request,self.template_name)

    
def signout(request):
    logout(request)
    return render(request,'dashboard/login.html')     
    
def dashboard(request):
    return render(request,'dashboard/base.html')

def index(request):

        user = User.objects.all()
        if request.method == 'POST':

                form = UserForm(request.POST,request.FILES)
                
                print(form)
                
                if form.is_valid()  :
                        form.save()
                        
                        return redirect('dash_board')
       
        form= UserForm()
        return render(request,'dashboard/user.html',{'form':form,'user':user})

def role(request):
        return render(request,'dashboard/role.html')

def general(request):
        store = Store.objects.all()
        if request.method == 'POST':
                form = StoreForm(request.POST,request.FILES)
                print(form)
                if form.is_valid()  :
                        form.save()
                        return redirect('general')
       
        form= StoreForm()
        return render(request,'dashboard/settings_general.html',{'store':store,'form':form})

def local(request):
        items = Local.objects.all()
        if request.method == 'POST':
                form = LocalForm(request.POST,request.FILES)
                print(form)
                if form.is_valid()  :
                        form.save()
                        return redirect('local')
       
        form= LocalForm()

        return render(request,'dashboard/settings_local.html',{'items':items,'form':form})

def server(request):
        return render(request,'dashboard/settings_server.html')

def stock(request):
        stocks = StockStatus.objects.all()
        if request.method == 'POST':
                form = StockStatusForm(request.POST,request.FILES)
                print(form)
                if form.is_valid()  :
                        form.save()
                        return redirect('stock')
       
        form= StockStatusForm()
        return render(request,'dashboard/settings_stock_status.html',{'stocks':stocks,'form':form})

def order_status(request):
        orders = OrderStatus.objects.all()
        if request.method == 'POST':
                form = OrderStatusForm(request.POST,request.FILES)
                print(form)
                if form.is_valid()  :
                        form.save()
                        return redirect('order_status')
       
        form= OrderStatusForm()


        return render(request,'dashboard/settings_order.html',{'orders':orders,'form':form})

def tax(request):
        taxes = Tax.objects.all()

        if request.method == 'POST':
                form = TaxForm(request.POST,request.FILES)
                print(form)
                if form.is_valid()  :
                        form.save()
                        return redirect('tax')
       
        form= TaxForm()
        return render(request,'dashboard/settings_tax.html',{'taxes':taxes,'form':form})

def currency(request):
        current = Coins.objects.all()
        if request.method == 'POST':
                form = CoinsForm(request.POST,request.FILES)
                print(form)
                if form.is_valid()  :
                        form.save()
                        return redirect('currency')
        form= CoinsForm()               
        return render(request,'dashboard/settings_currency.html',{'current':current,'form':form})

def detail(request,id):
        detail = Table_user.objects.get(id=id)
        return render(request,'dashboard/users_detail.html',{'detail':detail})

def social(request):
        icons = Social.objects.all()
        if request.method == 'POST':
                form = SocialForm(request.POST,request.FILES)
                print(form)
                if form.is_valid()  :
                        form.save()
                        return redirect('social')
       
        form= SocialForm()

        return render(request,'dashboard/social.html',{'icons':icons,'form':form})

class UserRoleCreateView(UserPassesTestMixin, CreateView):
    model = Role
    form_class = RoleForm
    template_name = 'dashboard/role.html'

    def test_func(self):
        return self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        data = super(UserRoleCreateView, self).get_context_data(**kwargs)
        users = [{'data': roll, 'edit_form': self.form_class(instance=roll)} for roll in self.model.objects.all()]
        data.update({"roles": users})
        data['roles']=Role.objects.all()
        return data

    def get_success_url(self):
        return reverse_lazy('role')

templates/dashboard/role.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}


<div class="row justify-content-lg-center">
    <div class="col-lg-12">
        <div class="card">
          <!-- Header -->
          <div class="card-header">
            <div class="row justify-content-between align-items-center flex-grow-1">
              <div class="col-12 col-md">
                <div class="d-flex justify-content-between align-items-center">
                  <h5 class="card-header-title">Roles</h5>
                </div>
              </div>
              <div class="col-auto">
                <a class="btn btn-primary" href="javascript:" data-bs-toggle="modal" data-bs-target="#addRole">
                    <i class="bi-person-plus-fill me-1"></i> Add Role
                </a>
            </div>
                <!-- Modal -->
                <div class="modal fade" id="addRole" data-bs-backdrop="static" tabindex="-1" role="dialog"
                aria-labelledby="staticBackdropLabel" aria-hidden="true">
               <div class="modal-dialog" role="document">
                   <div class="modal-content">
                       <div class="modal-header">
                           <h5 class="modal-title" id="staticBackdropLabel">Add New Role</h5>
                           <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                       </div>
                       <div class="modal-body">
                           <form method="post">
                               {% csrf_token %}
                               {% if form.non_field_errors %}
                                   <div class="alert alert-danger" role="alert">
                                       {% for error in form.non_field_errors %}
                                           {{ error }}
                                       {% endfor %}
                                   </div>
                               {% endif %}
   
                               <div class="mb-3">
                                   <label class="form-label" for="id_title">Role title</label>
                                   {{ form.name }}
                                   {% for error in form.name.errors %}
                                       <span class="invalid-feedback">{{ error }}</span>
                                   {% endfor %}
                               </div>
   
                               <div class="mb-3">
                                   <label class="form-label" for="exampleFormControlInput1">Role Permission</label>
                                   <!-- Checkbox -->
                                   <div class="form-check mb-3">
                                       {{ form.order }}
                                       <label class="form-check-label" for="id_accounts">Order</label>
                                   </div>
                                   <!-- End Checkbox -->
   
                                   <!-- Checkbox -->
                                   <div class="form-check mb-3">
                                       {{ form.catolog}}
                                       <label class="form-check-label" for="id_hr">Catolog</label>
                                   </div>
                                   <!-- End Checkbox -->
   
                                   <!-- Checkbox -->
                                   <div class="form-check mb-3">
                                       {{ form.pages }}
                                       <label class="form-check-label" for="id_purchase">Pages</label>
                                   </div>
   
                                   <!-- Checkbox -->
                                   <div class="form-check mb-3">
                                       {{ form.subscribers_list }}
                                       <label class="form-check-label" for="id_sales">Subscribers_list</label>
                                   </div>
                                   <!-- End Checkbox -->
   
   
                                   <!-- Checkbox -->
                                   <div class="form-check mb-3">
                                       {{ form.report }}
                                       <label class="form-check-label" for="id_work_site">Report</label>
                                   </div>
                                   <!-- End Checkbox -->
                                   <!-- <div class="row mx-3">
                                       {% for worksite in form.work_sites %}
                                           <div class="col-4">
                                               <!-- Checkbox -->
                                               <!-- <div class="form-check mb-3">
                                                   {{ worksite }}
                                                   <label class="form-check-label"
                                                          for="id_work_site{{ forloop.counter0 }}">Site 1</label>
                                               </div> -->
                                               <!-- End Checkbox -->
                                           </div> 
                                       {% endfor %}
   
                                   </div>
                                   <!-- Checkbox -->
                                   <!-- <div class="form-check mb-3">
   
                                       {{ form.report }}
                                       <label class="form-check-label" for="id_report">Report</label>
                                   </div> -->
                                   <!-- End Checkbox -->
                               </div>
   
                       </div>
                       <div class="modal-footer">
                           <button type="button" class="btn btn-white" data-bs-dismiss="modal">Close</button>
                           <button type="submit" class="btn btn-primary">Create Role</button>
                       </div>
                       </form>
                   </div>
               </div>
           </div>
           <!-- End Modal -->
       </div>
              
            </div>



            <!-- Table -->
            <div class="table-responsive datatable-custom">
            <table class="js-datatable table table-borderless table-thead-bordered table-nowrap table-align-middle card-table"
                data-hs-datatables-options='{
                        "order": [],
                        "search": "#datatableWithSearchInput",
                        "isResponsive": false,
                        "isShowPaging": true,
                        "pagination": "datatablePagination"
                        }'>
            <thead class="thead-light">
            <tr class="text-center">
                <th>ID</th>
                <th>Name</th>
                <th>Created</th>
                <th>Action</th>
                
            </thead>

            <tbody>
               {% for item in roles %}                     
            <tr class="text-center">
                <td>{{item.id}}</td>
                <td class="text-center">
                    <a class="d-flex justify-content-center" href="user-view.php?user=1">
                    <div class="avatar avatar-circle">
                        <!-- <img class="avatar-img" src="../uploads/user.webp" alt="Image Description"> -->
                    </div>
                    <div class="ms-3">
                        <span class="d-block fs-5 text-inherit mb-0">{{item.name}} </span>
                        
                    </div>
                    </a>
                </td>
                
                 <td><span class="d-block fs-5 text-body">{{item.created}}</span></td> 
                
                
                
                <td class="text-center">
                    <div class="btn-group" role="group">
                        <a class="btn btn-white btn-sm" href="#">
                        <i class="bi-pencil-fill me-1"></i> Edit
                        </a>

                        <!-- Button Group -->
                        <div class="btn-group">
                        <button type="button" class="btn btn-white btn-icon btn-sm dropdown-toggle dropdown-toggle-empty" id="productsEditDropdown8" data-bs-toggle="dropdown" aria-expanded="false"></button>

                        <div class="dropdown-menu dropdown-menu-end mt-1" aria-labelledby="productsEditDropdown8">
                            <a class="dropdown-item" href="#">
                            <i class="bi-eye dropdown-item-icon"></i> View
                            </a>
                            <a class="dropdown-item" href="#">
                            <i class="bi-fingerprint dropdown-item-icon"></i> Reset Password
                            </a>
                            <a class="dropdown-item" href="#">
                            <i class="bi-lock dropdown-item-icon"></i> Suspend User
                            </a>
                        </div>
                        </div>
                        <!-- End Button Group -->
                    </div>	
                </td>
            </tr>
           {% endfor %}                         
          </tbody>

        </table>
        </div>


        </div>
        </div>
      </div>
  </div>
        


{% endblock %}

templates/dashboard/settings_server.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}


<div class="row justify-content-lg-center">
    <div class="col-lg-12">
        <div class="card">
          <!-- Header -->
          <div class="card-header">
            <div class="row justify-content-between align-items-center flex-grow-1">
              <div class="col-12 col-md">
                <div class="d-flex justify-content-between align-items-center">
                  <h5 class="card-header-title"></h5>
                </div>
              </div>

              <div class="col-auto">
                <a class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#AddCategories">
                  <i class="bi-plus-circle me-1"></i> Add New 
                </a>
                </div>
                <!-- Modal -->
                <div class="modal fade" id="AddCategories" data-bs-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Add New Categories</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                    <form action="adminaction.php" method="post" enctype="multipart/form-data">
                      <div class="mb-3">
                      <label class="form-label" for="catname">Category Name</label>
                      <input type="text" id="catname" name="catname" class="form-control" placeholder="Category Name">
                      </div>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-white" data-bs-dismiss="modal">Close</button>
                    <button type="submit" name="AddNewCategory" class="btn btn-primary">Save</button>
                    </div>
                  </div>
                  </div>
                </div>


						  
						  
						  
					  </div>
					  
					  
					</div>
				  </div>
				</div>

              
            </div>



            <!-- Table -->
            <div class="table-responsive datatable-custom">
            <table class="js-datatable table table-borderless table-thead-bordered table-nowrap table-align-middle card-table"
                data-hs-datatables-options='{
                        "order": [],
                        "search": "#datatableWithSearchInput",
                        "isResponsive": false,
                        "isShowPaging": true,
                        "pagination": "datatablePagination"
                        }'>
            <thead class="thead-light">
            <tr class="text-center">
                <th>Maintenance Mode</th>
                <th>Active/Deactive</th>
                
                
            </thead>

            <tbody>
                                    
            <tr class="text-center">
                <td>1</td>
                <td class="text-center">
                    <a class="d-flex justify-content-center" href="user-view.php?user=1">
                    <div class="avatar avatar-circle">
                        <!-- <img class="avatar-img" src="../uploads/user.webp" alt="Image Description"> -->
                    </div>
                    <div class="ms-3">
                        <span class="d-block fs-5 text-inherit mb-0">Web Admin </span>
                        
                    </div>
                    </a>
                </td>
                
                
            </tr>

        </tbody>

    </table>
    </div>


    </div>
    </div>
  </div>
</div>
    
                                    
            


{% endblock %}